[background]
path = "/usr/share/backgrounds/wallpaper.png"
fit = "Contain"

# The entries defined in this section will be passed to the session as environment variables when it is started
[env]
ENV_VARIABLE = "value"

[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true

theme_name = "Dracula"
cursor_theme_name = "Dracula-cursor"
icon_theme_name = "Dracula"
font_name = "Cantarell 16"

cursor_blink = true

[commands]
# The command used to reboot the system
reboot = ["systemctl", "reboot"]
# The command used to shut down the system
poweroff = ["systemctl", "poweroff"]
# The command prefix for X11 sessions to start the X server
x11_prefix = [ "startx", "/usr/bin/env" ]

[appearance]
# The message that initially displays on startup
#greeting_msg = "Welcome back!"


[widget.clock]
# strftime format argument
# See https://docs.rs/jiff/0.1.14/jiff/fmt/strtime/index.html#conversion-specifications
format = "%a %H:%M"

# How often to update the text
resolution = "500ms"

# Ask GTK to make the label at least this wide. This helps keeps the parent element layout and width consistent.
# Experiment with different widths, the interpretation of this value is entirely up to GTK.
label_width = 150
