x-common-service-defaults: &common-service-defaults
  restart: unless-stopped
  logging:
    driver: "json-file"
    options:
      max-size: ${LOG_MAX_SIZE:-200k}
      max-file: ${LOG_MAX_FILE:-5}
secrets:
  CF_TOKEN:
    file: ../common/docker/secrets/cf_token
volumes:
  traefik-data:

x-hardened: &hardened
  read_only: true
  security_opt:
    - no-new-privileges:true
  cap_drop:
    - NET_RAW

services:
  traefik:
    image: traefik
    container_name: traefik
    <<: [*common-service-defaults, *hardened]
    user: "65534:65534"
    ports:
      - 80:80
      - 443:443
    volumes:
      - traefik-data:/data
      - /var/lib/docker-services/volumes/traefik:/etc/traefik:ro
      - "socket-proxy.run:/run/proxy"
    networks:
      files_default:
      affine_net:
        aliases: ["authelia.${DOMAIN}"]
      outline_net:
        aliases: ["authelia.${DOMAIN}"]
      immich_net:
        aliases: ["authelia.${DOMAIN}"]
      authelia_net:
      mirrors_net:
      monitoring_net:
    secrets:
      - CF_TOKEN
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/CF_TOKEN
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=authelia@docker"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)"
    sysctls:
      net.ipv4.ip_unprivileged_port_start: 80
    depends_on:
      init-volumes:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  files_default:
    external: true
  affine_net: {}
  outline_net: {}
  immich_net: {}
  authelia_net: {}
  monitoring_net: {}
